* Create a github repo 
* clone a suzugy
* create content
* share content
* assessment

In [16]:
1+2

3

In [17]:
import numpy as np
import scipy.linalg as lg


In [18]:
4+67

71

In [19]:
n=10
A=2*np.eye(n)+np.diag(4*np.ones(n-1),1)
print(A)

[[2. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]]


In [22]:
A**4-A**2


array([[ 12., 240.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  12., 240.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  12., 240.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  12., 240.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  12., 240.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  12., 240.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  12., 240.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  12., 240.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12., 240.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.]])